rt-main:
  user: root
  hostname: ws.rt.gw
  deploy_path: /opt/easyengine/sites/rt-webstories.rt.gw/app

google-main:
  user: root
  hostname: ws.rt.gw
  deploy_path: /opt/easyengine/sites/google-webstories.rt.gw/app
