version: 1
snapshot:
  widths: [1600]
  min-height: 1000
  percy-css: |
    .toplevel_page_amp-options, #footer-upgrade {
      display: none;
    }
    span.update-plugins {
      display: none !important;
    }
